export enum IProficiencyType {
    Athletics = 'Athletics',
    Arobatic = 'Arobatics',
    SleightOfHand = 'Sleight of Hand',
    Stealth = 'Stealth',
    Arcana = 'Arcana',
    History = 'History',
    Investigation = 'Investigation',
    Nature = 'Nature',
    Religion = 'Religion',
    AnimalHandling = 'Animal Handling',
    Insight = 'Insight',
    Medicine = 'Medicine',
    Perception = 'Perception',
    Survival = 'Survival',
    Deception = 'Deception',
    Intimidation = 'Intimidation',
    Performance = 'Performance',
    Persuasion = 'Persuasion',
}
